// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }



// import type { Metadata } from "next";

// export const dashboardMetadata: Metadata = {
//   title: "Dashboard - Create Next App",
//   description: "Generated by create next app",
// };


// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }





import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { AuthProvider } from "../contexts/AuthContext"; 

const inter = Inter({ subsets: ["latin"] });

export const dashboardMetadata: Metadata = {
  title: "Dashboard - Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <AuthProvider> {/* Wrap content with AuthProvider */}
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    // </AuthProvider>
  );
}
