"""added sites and some data to model

Revision ID: 24efdf9460ef
Revises: f41f73325209
Create Date: 2024-04-16 10:16:53.796477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24efdf9460ef'
down_revision = 'f41f73325209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('company_logo', sa.String(), nullable=True),
    sa.Column('site_url', sa.String(), nullable=True),
    sa.Column('company_description', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('tot_desktop_audits', sa.Integer(), nullable=True),
    sa.Column('tot_mobile_audits', sa.Integer(), nullable=True),
    sa.Column('tot_app_audits', sa.Integer(), nullable=True),
    sa.Column('total_datapoints', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_sites',
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('related_site_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('site_id', 'related_site_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_sites')
    op.drop_table('site')
    # ### end Alembic commands ###
