"""added rankings.

Revision ID: ec4025e7ce47
Revises: 24efdf9460ef
Create Date: 2024-04-16 21:19:03.142183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4025e7ce47'
down_revision = '24efdf9460ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('absolute_rank', sa.String(), nullable=True),
    sa.Column('industry_rank', sa.String(), nullable=True),
    sa.Column('absolute_usability_rank', sa.String(), nullable=True),
    sa.Column('industry_usability_rank', sa.String(), nullable=True),
    sa.Column('absolute_accessibility_rank', sa.String(), nullable=True),
    sa.Column('industry_accessibility_rank', sa.String(), nullable=True),
    sa.Column('absolute_performance_rank', sa.String(), nullable=True),
    sa.Column('industry_performance_rank', sa.String(), nullable=True),
    sa.Column('absolute_sentiment_rank', sa.String(), nullable=True),
    sa.Column('industry_sentiment_rank', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('related_sites')
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('languages', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('markets', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('markets')
        batch_op.drop_column('languages')

    op.create_table('related_sites',
    sa.Column('site_id', sa.VARCHAR(), nullable=False),
    sa.Column('related_site_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('site_id', 'related_site_id')
    )
    op.drop_table('rankings')
    # ### end Alembic commands ###
